apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kubia
  name: kubia
spec:
  containers:
  - image: kubia:v0.1
    name: kubia
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
