apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kubia
  name: kubia-http
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: kubia
  type: LoadBalancer
status:
  loadBalancer: {}
