apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynginx-rs
  labels:
    run: nginx
spec:
  template:
    metadata:
      name: myapp
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:hostname
  replicas: 2
  selector:
    matchLabels:
      run: nginx
