apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-http
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
